# Generated by Django 2.0.4 on 2018-04-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_customers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
