# Generated by Django 2.0.4 on 2018-04-23 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180423_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='polls.Question'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='userProfile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
